package com.scrappy.sites;

import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;

import com.anupams.protogen.Scrape.Element;
import com.anupams.protogen.Scrape.Element.By;
import com.anupams.protogen.Scrape.Relative;
import com.anupams.protogen.Scrape.Step;

import java.util.Arrays;
import java.util.List;

/**
 * TODO: Insert description here. (generated by anupams)
 */
public class BaseConfig implements Config {

  @Override
  public Element addRelativeElements(Element existingElement, Relative... relatives) {
    if (null != relatives) {
      return existingElement.toBuilder().addAllRelativeElement(Arrays.asList(relatives)).build();
    }
    return existingElement;
  }

  @Override
  public Element addRelativeElements(Element existingElement, List<Relative> relatives) {
    if (null != relatives && !relatives.isEmpty()) {
      return existingElement.toBuilder().addAllRelativeElement(relatives).build();
    }
    return existingElement;
  }

  @Override
  public Element buildElement(String id, By searchElementBy, String value) {
    return buildElement(id, searchElementBy, value, Lists.<Relative>newArrayList());
  }

  @Override
  public Element buildElement(String id, By searchElementBy, String value,
      List<Relative> relatives) {
    Preconditions.checkArgument(!Strings.isNullOrEmpty(id), "Id can not be null");
    Preconditions.checkArgument(!Strings.isNullOrEmpty(value), "value can not be null");

    Element.Builder element = Element.newBuilder();
    element.setId(id).setSearchBy(searchElementBy).setValue(value);
    if (null != relatives && !relatives.isEmpty()) {
      element.addAllRelativeElement(relatives);
    }
    return element.build();
  }

  @Override
  public Element buildElement(String id, By searchElementBy, String value,
      Relative... relatives) {
    List<Relative> relations = Lists.newArrayList();
    if (null != relatives) {
      relations = Arrays.asList(relatives);
    }
    return buildElement(id, searchElementBy, value, relations);
  }

  @Override
  public List<Step> constructConfig() {
    //TODO(anupam): Create a custom exception.
    throw new IllegalStateException(" Method not implemented");
  }
}
