// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scrape.proto

package com.anupams.protogen;

public final class Scrape {
  private Scrape() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StepOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.anupams.protogen.Step.Type step_type = 1;
    boolean hasStepType();
    com.anupams.protogen.Scrape.Step.Type getStepType();
    
    // repeated .com.anupams.protogen.Element element = 2;
    java.util.List<com.anupams.protogen.Scrape.Element> 
        getElementList();
    com.anupams.protogen.Scrape.Element getElement(int index);
    int getElementCount();
    java.util.List<? extends com.anupams.protogen.Scrape.ElementOrBuilder> 
        getElementOrBuilderList();
    com.anupams.protogen.Scrape.ElementOrBuilder getElementOrBuilder(
        int index);
  }
  public static final class Step extends
      com.google.protobuf.GeneratedMessage
      implements StepOrBuilder {
    // Use Step.newBuilder() to construct.
    private Step(Builder builder) {
      super(builder);
    }
    private Step(boolean noInit) {}
    
    private static final Step defaultInstance;
    public static Step getDefaultInstance() {
      return defaultInstance;
    }
    
    public Step getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Step_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Step_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      NAVIGATE(0, 1),
      SCRAPE(1, 2),
      PAGINATED(2, 3),
      ;
      
      public static final int NAVIGATE_VALUE = 1;
      public static final int SCRAPE_VALUE = 2;
      public static final int PAGINATED_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return NAVIGATE;
          case 2: return SCRAPE;
          case 3: return PAGINATED;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.anupams.protogen.Scrape.Step.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        NAVIGATE, SCRAPE, PAGINATED, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.anupams.protogen.Step.Type)
    }
    
    private int bitField0_;
    // required .com.anupams.protogen.Step.Type step_type = 1;
    public static final int STEP_TYPE_FIELD_NUMBER = 1;
    private com.anupams.protogen.Scrape.Step.Type stepType_;
    public boolean hasStepType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.anupams.protogen.Scrape.Step.Type getStepType() {
      return stepType_;
    }
    
    // repeated .com.anupams.protogen.Element element = 2;
    public static final int ELEMENT_FIELD_NUMBER = 2;
    private java.util.List<com.anupams.protogen.Scrape.Element> element_;
    public java.util.List<com.anupams.protogen.Scrape.Element> getElementList() {
      return element_;
    }
    public java.util.List<? extends com.anupams.protogen.Scrape.ElementOrBuilder> 
        getElementOrBuilderList() {
      return element_;
    }
    public int getElementCount() {
      return element_.size();
    }
    public com.anupams.protogen.Scrape.Element getElement(int index) {
      return element_.get(index);
    }
    public com.anupams.protogen.Scrape.ElementOrBuilder getElementOrBuilder(
        int index) {
      return element_.get(index);
    }
    
    private void initFields() {
      stepType_ = com.anupams.protogen.Scrape.Step.Type.NAVIGATE;
      element_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStepType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getElementCount(); i++) {
        if (!getElement(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, stepType_.getNumber());
      }
      for (int i = 0; i < element_.size(); i++) {
        output.writeMessage(2, element_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, stepType_.getNumber());
      }
      for (int i = 0; i < element_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.anupams.protogen.Scrape.Step parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Step parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Step parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Step parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Step parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Step parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Step parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.anupams.protogen.Scrape.Step parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.anupams.protogen.Scrape.Step parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Step parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.anupams.protogen.Scrape.Step prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.anupams.protogen.Scrape.StepOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Step_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Step_fieldAccessorTable;
      }
      
      // Construct using com.anupams.protogen.Scrape.Step.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getElementFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        stepType_ = com.anupams.protogen.Scrape.Step.Type.NAVIGATE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (elementBuilder_ == null) {
          element_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          elementBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.anupams.protogen.Scrape.Step.getDescriptor();
      }
      
      public com.anupams.protogen.Scrape.Step getDefaultInstanceForType() {
        return com.anupams.protogen.Scrape.Step.getDefaultInstance();
      }
      
      public com.anupams.protogen.Scrape.Step build() {
        com.anupams.protogen.Scrape.Step result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.anupams.protogen.Scrape.Step buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.anupams.protogen.Scrape.Step result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.anupams.protogen.Scrape.Step buildPartial() {
        com.anupams.protogen.Scrape.Step result = new com.anupams.protogen.Scrape.Step(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stepType_ = stepType_;
        if (elementBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            element_ = java.util.Collections.unmodifiableList(element_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.element_ = element_;
        } else {
          result.element_ = elementBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.anupams.protogen.Scrape.Step) {
          return mergeFrom((com.anupams.protogen.Scrape.Step)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.anupams.protogen.Scrape.Step other) {
        if (other == com.anupams.protogen.Scrape.Step.getDefaultInstance()) return this;
        if (other.hasStepType()) {
          setStepType(other.getStepType());
        }
        if (elementBuilder_ == null) {
          if (!other.element_.isEmpty()) {
            if (element_.isEmpty()) {
              element_ = other.element_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureElementIsMutable();
              element_.addAll(other.element_);
            }
            onChanged();
          }
        } else {
          if (!other.element_.isEmpty()) {
            if (elementBuilder_.isEmpty()) {
              elementBuilder_.dispose();
              elementBuilder_ = null;
              element_ = other.element_;
              bitField0_ = (bitField0_ & ~0x00000002);
              elementBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getElementFieldBuilder() : null;
            } else {
              elementBuilder_.addAllMessages(other.element_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStepType()) {
          
          return false;
        }
        for (int i = 0; i < getElementCount(); i++) {
          if (!getElement(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.anupams.protogen.Scrape.Step.Type value = com.anupams.protogen.Scrape.Step.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                stepType_ = value;
              }
              break;
            }
            case 18: {
              com.anupams.protogen.Scrape.Element.Builder subBuilder = com.anupams.protogen.Scrape.Element.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addElement(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.anupams.protogen.Step.Type step_type = 1;
      private com.anupams.protogen.Scrape.Step.Type stepType_ = com.anupams.protogen.Scrape.Step.Type.NAVIGATE;
      public boolean hasStepType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.anupams.protogen.Scrape.Step.Type getStepType() {
        return stepType_;
      }
      public Builder setStepType(com.anupams.protogen.Scrape.Step.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        stepType_ = value;
        onChanged();
        return this;
      }
      public Builder clearStepType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stepType_ = com.anupams.protogen.Scrape.Step.Type.NAVIGATE;
        onChanged();
        return this;
      }
      
      // repeated .com.anupams.protogen.Element element = 2;
      private java.util.List<com.anupams.protogen.Scrape.Element> element_ =
        java.util.Collections.emptyList();
      private void ensureElementIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          element_ = new java.util.ArrayList<com.anupams.protogen.Scrape.Element>(element_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.anupams.protogen.Scrape.Element, com.anupams.protogen.Scrape.Element.Builder, com.anupams.protogen.Scrape.ElementOrBuilder> elementBuilder_;
      
      public java.util.List<com.anupams.protogen.Scrape.Element> getElementList() {
        if (elementBuilder_ == null) {
          return java.util.Collections.unmodifiableList(element_);
        } else {
          return elementBuilder_.getMessageList();
        }
      }
      public int getElementCount() {
        if (elementBuilder_ == null) {
          return element_.size();
        } else {
          return elementBuilder_.getCount();
        }
      }
      public com.anupams.protogen.Scrape.Element getElement(int index) {
        if (elementBuilder_ == null) {
          return element_.get(index);
        } else {
          return elementBuilder_.getMessage(index);
        }
      }
      public Builder setElement(
          int index, com.anupams.protogen.Scrape.Element value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.set(index, value);
          onChanged();
        } else {
          elementBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setElement(
          int index, com.anupams.protogen.Scrape.Element.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.set(index, builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addElement(com.anupams.protogen.Scrape.Element value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.add(value);
          onChanged();
        } else {
          elementBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addElement(
          int index, com.anupams.protogen.Scrape.Element value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.add(index, value);
          onChanged();
        } else {
          elementBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addElement(
          com.anupams.protogen.Scrape.Element.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.add(builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addElement(
          int index, com.anupams.protogen.Scrape.Element.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.add(index, builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllElement(
          java.lang.Iterable<? extends com.anupams.protogen.Scrape.Element> values) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          super.addAll(values, element_);
          onChanged();
        } else {
          elementBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearElement() {
        if (elementBuilder_ == null) {
          element_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          elementBuilder_.clear();
        }
        return this;
      }
      public Builder removeElement(int index) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.remove(index);
          onChanged();
        } else {
          elementBuilder_.remove(index);
        }
        return this;
      }
      public com.anupams.protogen.Scrape.Element.Builder getElementBuilder(
          int index) {
        return getElementFieldBuilder().getBuilder(index);
      }
      public com.anupams.protogen.Scrape.ElementOrBuilder getElementOrBuilder(
          int index) {
        if (elementBuilder_ == null) {
          return element_.get(index);  } else {
          return elementBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.anupams.protogen.Scrape.ElementOrBuilder> 
           getElementOrBuilderList() {
        if (elementBuilder_ != null) {
          return elementBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(element_);
        }
      }
      public com.anupams.protogen.Scrape.Element.Builder addElementBuilder() {
        return getElementFieldBuilder().addBuilder(
            com.anupams.protogen.Scrape.Element.getDefaultInstance());
      }
      public com.anupams.protogen.Scrape.Element.Builder addElementBuilder(
          int index) {
        return getElementFieldBuilder().addBuilder(
            index, com.anupams.protogen.Scrape.Element.getDefaultInstance());
      }
      public java.util.List<com.anupams.protogen.Scrape.Element.Builder> 
           getElementBuilderList() {
        return getElementFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.anupams.protogen.Scrape.Element, com.anupams.protogen.Scrape.Element.Builder, com.anupams.protogen.Scrape.ElementOrBuilder> 
          getElementFieldBuilder() {
        if (elementBuilder_ == null) {
          elementBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.anupams.protogen.Scrape.Element, com.anupams.protogen.Scrape.Element.Builder, com.anupams.protogen.Scrape.ElementOrBuilder>(
                  element_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          element_ = null;
        }
        return elementBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.anupams.protogen.Step)
    }
    
    static {
      defaultInstance = new Step(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.anupams.protogen.Step)
  }
  
  public interface ElementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required .com.anupams.protogen.Element.By search_by = 2;
    boolean hasSearchBy();
    com.anupams.protogen.Scrape.Element.By getSearchBy();
    
    // required string value = 3;
    boolean hasValue();
    String getValue();
    
    // repeated .com.anupams.protogen.Relative relative_element = 4;
    java.util.List<com.anupams.protogen.Scrape.Relative> 
        getRelativeElementList();
    com.anupams.protogen.Scrape.Relative getRelativeElement(int index);
    int getRelativeElementCount();
    java.util.List<? extends com.anupams.protogen.Scrape.RelativeOrBuilder> 
        getRelativeElementOrBuilderList();
    com.anupams.protogen.Scrape.RelativeOrBuilder getRelativeElementOrBuilder(
        int index);
  }
  public static final class Element extends
      com.google.protobuf.GeneratedMessage
      implements ElementOrBuilder {
    // Use Element.newBuilder() to construct.
    private Element(Builder builder) {
      super(builder);
    }
    private Element(boolean noInit) {}
    
    private static final Element defaultInstance;
    public static Element getDefaultInstance() {
      return defaultInstance;
    }
    
    public Element getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Element_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Element_fieldAccessorTable;
    }
    
    public enum By
        implements com.google.protobuf.ProtocolMessageEnum {
      XPATH(0, 0),
      CSS(1, 1),
      ID(2, 2),
      CLASS(3, 3),
      ;
      
      public static final int XPATH_VALUE = 0;
      public static final int CSS_VALUE = 1;
      public static final int ID_VALUE = 2;
      public static final int CLASS_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static By valueOf(int value) {
        switch (value) {
          case 0: return XPATH;
          case 1: return CSS;
          case 2: return ID;
          case 3: return CLASS;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<By>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<By>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<By>() {
              public By findValueByNumber(int number) {
                return By.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.anupams.protogen.Scrape.Element.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final By[] VALUES = {
        XPATH, CSS, ID, CLASS, 
      };
      
      public static By valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private By(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.anupams.protogen.Element.By)
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .com.anupams.protogen.Element.By search_by = 2;
    public static final int SEARCH_BY_FIELD_NUMBER = 2;
    private com.anupams.protogen.Scrape.Element.By searchBy_;
    public boolean hasSearchBy() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.anupams.protogen.Scrape.Element.By getSearchBy() {
      return searchBy_;
    }
    
    // required string value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.anupams.protogen.Relative relative_element = 4;
    public static final int RELATIVE_ELEMENT_FIELD_NUMBER = 4;
    private java.util.List<com.anupams.protogen.Scrape.Relative> relativeElement_;
    public java.util.List<com.anupams.protogen.Scrape.Relative> getRelativeElementList() {
      return relativeElement_;
    }
    public java.util.List<? extends com.anupams.protogen.Scrape.RelativeOrBuilder> 
        getRelativeElementOrBuilderList() {
      return relativeElement_;
    }
    public int getRelativeElementCount() {
      return relativeElement_.size();
    }
    public com.anupams.protogen.Scrape.Relative getRelativeElement(int index) {
      return relativeElement_.get(index);
    }
    public com.anupams.protogen.Scrape.RelativeOrBuilder getRelativeElementOrBuilder(
        int index) {
      return relativeElement_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      searchBy_ = com.anupams.protogen.Scrape.Element.By.XPATH;
      value_ = "";
      relativeElement_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSearchBy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRelativeElementCount(); i++) {
        if (!getRelativeElement(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, searchBy_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getValueBytes());
      }
      for (int i = 0; i < relativeElement_.size(); i++) {
        output.writeMessage(4, relativeElement_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, searchBy_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getValueBytes());
      }
      for (int i = 0; i < relativeElement_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, relativeElement_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.anupams.protogen.Scrape.Element parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Element parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Element parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Element parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Element parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Element parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Element parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.anupams.protogen.Scrape.Element parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.anupams.protogen.Scrape.Element parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Element parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.anupams.protogen.Scrape.Element prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.anupams.protogen.Scrape.ElementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Element_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Element_fieldAccessorTable;
      }
      
      // Construct using com.anupams.protogen.Scrape.Element.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRelativeElementFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        searchBy_ = com.anupams.protogen.Scrape.Element.By.XPATH;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (relativeElementBuilder_ == null) {
          relativeElement_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          relativeElementBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.anupams.protogen.Scrape.Element.getDescriptor();
      }
      
      public com.anupams.protogen.Scrape.Element getDefaultInstanceForType() {
        return com.anupams.protogen.Scrape.Element.getDefaultInstance();
      }
      
      public com.anupams.protogen.Scrape.Element build() {
        com.anupams.protogen.Scrape.Element result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.anupams.protogen.Scrape.Element buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.anupams.protogen.Scrape.Element result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.anupams.protogen.Scrape.Element buildPartial() {
        com.anupams.protogen.Scrape.Element result = new com.anupams.protogen.Scrape.Element(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.searchBy_ = searchBy_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (relativeElementBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            relativeElement_ = java.util.Collections.unmodifiableList(relativeElement_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.relativeElement_ = relativeElement_;
        } else {
          result.relativeElement_ = relativeElementBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.anupams.protogen.Scrape.Element) {
          return mergeFrom((com.anupams.protogen.Scrape.Element)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.anupams.protogen.Scrape.Element other) {
        if (other == com.anupams.protogen.Scrape.Element.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSearchBy()) {
          setSearchBy(other.getSearchBy());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (relativeElementBuilder_ == null) {
          if (!other.relativeElement_.isEmpty()) {
            if (relativeElement_.isEmpty()) {
              relativeElement_ = other.relativeElement_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureRelativeElementIsMutable();
              relativeElement_.addAll(other.relativeElement_);
            }
            onChanged();
          }
        } else {
          if (!other.relativeElement_.isEmpty()) {
            if (relativeElementBuilder_.isEmpty()) {
              relativeElementBuilder_.dispose();
              relativeElementBuilder_ = null;
              relativeElement_ = other.relativeElement_;
              bitField0_ = (bitField0_ & ~0x00000008);
              relativeElementBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRelativeElementFieldBuilder() : null;
            } else {
              relativeElementBuilder_.addAllMessages(other.relativeElement_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasSearchBy()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        for (int i = 0; i < getRelativeElementCount(); i++) {
          if (!getRelativeElement(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.anupams.protogen.Scrape.Element.By value = com.anupams.protogen.Scrape.Element.By.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                searchBy_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
            case 34: {
              com.anupams.protogen.Scrape.Relative.Builder subBuilder = com.anupams.protogen.Scrape.Relative.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRelativeElement(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required .com.anupams.protogen.Element.By search_by = 2;
      private com.anupams.protogen.Scrape.Element.By searchBy_ = com.anupams.protogen.Scrape.Element.By.XPATH;
      public boolean hasSearchBy() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.anupams.protogen.Scrape.Element.By getSearchBy() {
        return searchBy_;
      }
      public Builder setSearchBy(com.anupams.protogen.Scrape.Element.By value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        searchBy_ = value;
        onChanged();
        return this;
      }
      public Builder clearSearchBy() {
        bitField0_ = (bitField0_ & ~0x00000002);
        searchBy_ = com.anupams.protogen.Scrape.Element.By.XPATH;
        onChanged();
        return this;
      }
      
      // required string value = 3;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
      }
      
      // repeated .com.anupams.protogen.Relative relative_element = 4;
      private java.util.List<com.anupams.protogen.Scrape.Relative> relativeElement_ =
        java.util.Collections.emptyList();
      private void ensureRelativeElementIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          relativeElement_ = new java.util.ArrayList<com.anupams.protogen.Scrape.Relative>(relativeElement_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.anupams.protogen.Scrape.Relative, com.anupams.protogen.Scrape.Relative.Builder, com.anupams.protogen.Scrape.RelativeOrBuilder> relativeElementBuilder_;
      
      public java.util.List<com.anupams.protogen.Scrape.Relative> getRelativeElementList() {
        if (relativeElementBuilder_ == null) {
          return java.util.Collections.unmodifiableList(relativeElement_);
        } else {
          return relativeElementBuilder_.getMessageList();
        }
      }
      public int getRelativeElementCount() {
        if (relativeElementBuilder_ == null) {
          return relativeElement_.size();
        } else {
          return relativeElementBuilder_.getCount();
        }
      }
      public com.anupams.protogen.Scrape.Relative getRelativeElement(int index) {
        if (relativeElementBuilder_ == null) {
          return relativeElement_.get(index);
        } else {
          return relativeElementBuilder_.getMessage(index);
        }
      }
      public Builder setRelativeElement(
          int index, com.anupams.protogen.Scrape.Relative value) {
        if (relativeElementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelativeElementIsMutable();
          relativeElement_.set(index, value);
          onChanged();
        } else {
          relativeElementBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRelativeElement(
          int index, com.anupams.protogen.Scrape.Relative.Builder builderForValue) {
        if (relativeElementBuilder_ == null) {
          ensureRelativeElementIsMutable();
          relativeElement_.set(index, builderForValue.build());
          onChanged();
        } else {
          relativeElementBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRelativeElement(com.anupams.protogen.Scrape.Relative value) {
        if (relativeElementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelativeElementIsMutable();
          relativeElement_.add(value);
          onChanged();
        } else {
          relativeElementBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRelativeElement(
          int index, com.anupams.protogen.Scrape.Relative value) {
        if (relativeElementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelativeElementIsMutable();
          relativeElement_.add(index, value);
          onChanged();
        } else {
          relativeElementBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRelativeElement(
          com.anupams.protogen.Scrape.Relative.Builder builderForValue) {
        if (relativeElementBuilder_ == null) {
          ensureRelativeElementIsMutable();
          relativeElement_.add(builderForValue.build());
          onChanged();
        } else {
          relativeElementBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRelativeElement(
          int index, com.anupams.protogen.Scrape.Relative.Builder builderForValue) {
        if (relativeElementBuilder_ == null) {
          ensureRelativeElementIsMutable();
          relativeElement_.add(index, builderForValue.build());
          onChanged();
        } else {
          relativeElementBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRelativeElement(
          java.lang.Iterable<? extends com.anupams.protogen.Scrape.Relative> values) {
        if (relativeElementBuilder_ == null) {
          ensureRelativeElementIsMutable();
          super.addAll(values, relativeElement_);
          onChanged();
        } else {
          relativeElementBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRelativeElement() {
        if (relativeElementBuilder_ == null) {
          relativeElement_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          relativeElementBuilder_.clear();
        }
        return this;
      }
      public Builder removeRelativeElement(int index) {
        if (relativeElementBuilder_ == null) {
          ensureRelativeElementIsMutable();
          relativeElement_.remove(index);
          onChanged();
        } else {
          relativeElementBuilder_.remove(index);
        }
        return this;
      }
      public com.anupams.protogen.Scrape.Relative.Builder getRelativeElementBuilder(
          int index) {
        return getRelativeElementFieldBuilder().getBuilder(index);
      }
      public com.anupams.protogen.Scrape.RelativeOrBuilder getRelativeElementOrBuilder(
          int index) {
        if (relativeElementBuilder_ == null) {
          return relativeElement_.get(index);  } else {
          return relativeElementBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.anupams.protogen.Scrape.RelativeOrBuilder> 
           getRelativeElementOrBuilderList() {
        if (relativeElementBuilder_ != null) {
          return relativeElementBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(relativeElement_);
        }
      }
      public com.anupams.protogen.Scrape.Relative.Builder addRelativeElementBuilder() {
        return getRelativeElementFieldBuilder().addBuilder(
            com.anupams.protogen.Scrape.Relative.getDefaultInstance());
      }
      public com.anupams.protogen.Scrape.Relative.Builder addRelativeElementBuilder(
          int index) {
        return getRelativeElementFieldBuilder().addBuilder(
            index, com.anupams.protogen.Scrape.Relative.getDefaultInstance());
      }
      public java.util.List<com.anupams.protogen.Scrape.Relative.Builder> 
           getRelativeElementBuilderList() {
        return getRelativeElementFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.anupams.protogen.Scrape.Relative, com.anupams.protogen.Scrape.Relative.Builder, com.anupams.protogen.Scrape.RelativeOrBuilder> 
          getRelativeElementFieldBuilder() {
        if (relativeElementBuilder_ == null) {
          relativeElementBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.anupams.protogen.Scrape.Relative, com.anupams.protogen.Scrape.Relative.Builder, com.anupams.protogen.Scrape.RelativeOrBuilder>(
                  relativeElement_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          relativeElement_ = null;
        }
        return relativeElementBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.anupams.protogen.Element)
    }
    
    static {
      defaultInstance = new Element(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.anupams.protogen.Element)
  }
  
  public interface RelativeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string parent_id = 1;
    boolean hasParentId();
    String getParentId();
    
    // repeated .com.anupams.protogen.Element elements = 2;
    java.util.List<com.anupams.protogen.Scrape.Element> 
        getElementsList();
    com.anupams.protogen.Scrape.Element getElements(int index);
    int getElementsCount();
    java.util.List<? extends com.anupams.protogen.Scrape.ElementOrBuilder> 
        getElementsOrBuilderList();
    com.anupams.protogen.Scrape.ElementOrBuilder getElementsOrBuilder(
        int index);
  }
  public static final class Relative extends
      com.google.protobuf.GeneratedMessage
      implements RelativeOrBuilder {
    // Use Relative.newBuilder() to construct.
    private Relative(Builder builder) {
      super(builder);
    }
    private Relative(boolean noInit) {}
    
    private static final Relative defaultInstance;
    public static Relative getDefaultInstance() {
      return defaultInstance;
    }
    
    public Relative getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Relative_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Relative_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string parent_id = 1;
    public static final int PARENT_ID_FIELD_NUMBER = 1;
    private java.lang.Object parentId_;
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getParentId() {
      java.lang.Object ref = parentId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          parentId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.anupams.protogen.Element elements = 2;
    public static final int ELEMENTS_FIELD_NUMBER = 2;
    private java.util.List<com.anupams.protogen.Scrape.Element> elements_;
    public java.util.List<com.anupams.protogen.Scrape.Element> getElementsList() {
      return elements_;
    }
    public java.util.List<? extends com.anupams.protogen.Scrape.ElementOrBuilder> 
        getElementsOrBuilderList() {
      return elements_;
    }
    public int getElementsCount() {
      return elements_.size();
    }
    public com.anupams.protogen.Scrape.Element getElements(int index) {
      return elements_.get(index);
    }
    public com.anupams.protogen.Scrape.ElementOrBuilder getElementsOrBuilder(
        int index) {
      return elements_.get(index);
    }
    
    private void initFields() {
      parentId_ = "";
      elements_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasParentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getElementsCount(); i++) {
        if (!getElements(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getParentIdBytes());
      }
      for (int i = 0; i < elements_.size(); i++) {
        output.writeMessage(2, elements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getParentIdBytes());
      }
      for (int i = 0; i < elements_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, elements_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.anupams.protogen.Scrape.Relative parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Relative parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Relative parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Relative parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Relative parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Relative parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.anupams.protogen.Scrape.Relative parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.anupams.protogen.Scrape.Relative parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.anupams.protogen.Scrape.Relative parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.anupams.protogen.Scrape.Relative parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.anupams.protogen.Scrape.Relative prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.anupams.protogen.Scrape.RelativeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Relative_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.anupams.protogen.Scrape.internal_static_com_anupams_protogen_Relative_fieldAccessorTable;
      }
      
      // Construct using com.anupams.protogen.Scrape.Relative.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getElementsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        parentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (elementsBuilder_ == null) {
          elements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          elementsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.anupams.protogen.Scrape.Relative.getDescriptor();
      }
      
      public com.anupams.protogen.Scrape.Relative getDefaultInstanceForType() {
        return com.anupams.protogen.Scrape.Relative.getDefaultInstance();
      }
      
      public com.anupams.protogen.Scrape.Relative build() {
        com.anupams.protogen.Scrape.Relative result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.anupams.protogen.Scrape.Relative buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.anupams.protogen.Scrape.Relative result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.anupams.protogen.Scrape.Relative buildPartial() {
        com.anupams.protogen.Scrape.Relative result = new com.anupams.protogen.Scrape.Relative(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.parentId_ = parentId_;
        if (elementsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            elements_ = java.util.Collections.unmodifiableList(elements_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.elements_ = elements_;
        } else {
          result.elements_ = elementsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.anupams.protogen.Scrape.Relative) {
          return mergeFrom((com.anupams.protogen.Scrape.Relative)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.anupams.protogen.Scrape.Relative other) {
        if (other == com.anupams.protogen.Scrape.Relative.getDefaultInstance()) return this;
        if (other.hasParentId()) {
          setParentId(other.getParentId());
        }
        if (elementsBuilder_ == null) {
          if (!other.elements_.isEmpty()) {
            if (elements_.isEmpty()) {
              elements_ = other.elements_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureElementsIsMutable();
              elements_.addAll(other.elements_);
            }
            onChanged();
          }
        } else {
          if (!other.elements_.isEmpty()) {
            if (elementsBuilder_.isEmpty()) {
              elementsBuilder_.dispose();
              elementsBuilder_ = null;
              elements_ = other.elements_;
              bitField0_ = (bitField0_ & ~0x00000002);
              elementsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getElementsFieldBuilder() : null;
            } else {
              elementsBuilder_.addAllMessages(other.elements_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasParentId()) {
          
          return false;
        }
        for (int i = 0; i < getElementsCount(); i++) {
          if (!getElements(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              parentId_ = input.readBytes();
              break;
            }
            case 18: {
              com.anupams.protogen.Scrape.Element.Builder subBuilder = com.anupams.protogen.Scrape.Element.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addElements(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string parent_id = 1;
      private java.lang.Object parentId_ = "";
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getParentId() {
        java.lang.Object ref = parentId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setParentId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        parentId_ = value;
        onChanged();
        return this;
      }
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      void setParentId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        parentId_ = value;
        onChanged();
      }
      
      // repeated .com.anupams.protogen.Element elements = 2;
      private java.util.List<com.anupams.protogen.Scrape.Element> elements_ =
        java.util.Collections.emptyList();
      private void ensureElementsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          elements_ = new java.util.ArrayList<com.anupams.protogen.Scrape.Element>(elements_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.anupams.protogen.Scrape.Element, com.anupams.protogen.Scrape.Element.Builder, com.anupams.protogen.Scrape.ElementOrBuilder> elementsBuilder_;
      
      public java.util.List<com.anupams.protogen.Scrape.Element> getElementsList() {
        if (elementsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(elements_);
        } else {
          return elementsBuilder_.getMessageList();
        }
      }
      public int getElementsCount() {
        if (elementsBuilder_ == null) {
          return elements_.size();
        } else {
          return elementsBuilder_.getCount();
        }
      }
      public com.anupams.protogen.Scrape.Element getElements(int index) {
        if (elementsBuilder_ == null) {
          return elements_.get(index);
        } else {
          return elementsBuilder_.getMessage(index);
        }
      }
      public Builder setElements(
          int index, com.anupams.protogen.Scrape.Element value) {
        if (elementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementsIsMutable();
          elements_.set(index, value);
          onChanged();
        } else {
          elementsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setElements(
          int index, com.anupams.protogen.Scrape.Element.Builder builderForValue) {
        if (elementsBuilder_ == null) {
          ensureElementsIsMutable();
          elements_.set(index, builderForValue.build());
          onChanged();
        } else {
          elementsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addElements(com.anupams.protogen.Scrape.Element value) {
        if (elementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementsIsMutable();
          elements_.add(value);
          onChanged();
        } else {
          elementsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addElements(
          int index, com.anupams.protogen.Scrape.Element value) {
        if (elementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementsIsMutable();
          elements_.add(index, value);
          onChanged();
        } else {
          elementsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addElements(
          com.anupams.protogen.Scrape.Element.Builder builderForValue) {
        if (elementsBuilder_ == null) {
          ensureElementsIsMutable();
          elements_.add(builderForValue.build());
          onChanged();
        } else {
          elementsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addElements(
          int index, com.anupams.protogen.Scrape.Element.Builder builderForValue) {
        if (elementsBuilder_ == null) {
          ensureElementsIsMutable();
          elements_.add(index, builderForValue.build());
          onChanged();
        } else {
          elementsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllElements(
          java.lang.Iterable<? extends com.anupams.protogen.Scrape.Element> values) {
        if (elementsBuilder_ == null) {
          ensureElementsIsMutable();
          super.addAll(values, elements_);
          onChanged();
        } else {
          elementsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearElements() {
        if (elementsBuilder_ == null) {
          elements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          elementsBuilder_.clear();
        }
        return this;
      }
      public Builder removeElements(int index) {
        if (elementsBuilder_ == null) {
          ensureElementsIsMutable();
          elements_.remove(index);
          onChanged();
        } else {
          elementsBuilder_.remove(index);
        }
        return this;
      }
      public com.anupams.protogen.Scrape.Element.Builder getElementsBuilder(
          int index) {
        return getElementsFieldBuilder().getBuilder(index);
      }
      public com.anupams.protogen.Scrape.ElementOrBuilder getElementsOrBuilder(
          int index) {
        if (elementsBuilder_ == null) {
          return elements_.get(index);  } else {
          return elementsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.anupams.protogen.Scrape.ElementOrBuilder> 
           getElementsOrBuilderList() {
        if (elementsBuilder_ != null) {
          return elementsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(elements_);
        }
      }
      public com.anupams.protogen.Scrape.Element.Builder addElementsBuilder() {
        return getElementsFieldBuilder().addBuilder(
            com.anupams.protogen.Scrape.Element.getDefaultInstance());
      }
      public com.anupams.protogen.Scrape.Element.Builder addElementsBuilder(
          int index) {
        return getElementsFieldBuilder().addBuilder(
            index, com.anupams.protogen.Scrape.Element.getDefaultInstance());
      }
      public java.util.List<com.anupams.protogen.Scrape.Element.Builder> 
           getElementsBuilderList() {
        return getElementsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.anupams.protogen.Scrape.Element, com.anupams.protogen.Scrape.Element.Builder, com.anupams.protogen.Scrape.ElementOrBuilder> 
          getElementsFieldBuilder() {
        if (elementsBuilder_ == null) {
          elementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.anupams.protogen.Scrape.Element, com.anupams.protogen.Scrape.Element.Builder, com.anupams.protogen.Scrape.ElementOrBuilder>(
                  elements_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          elements_ = null;
        }
        return elementsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.anupams.protogen.Relative)
    }
    
    static {
      defaultInstance = new Relative(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.anupams.protogen.Relative)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_anupams_protogen_Step_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_anupams_protogen_Step_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_anupams_protogen_Element_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_anupams_protogen_Element_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_anupams_protogen_Relative_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_anupams_protogen_Relative_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014scrape.proto\022\024com.anupams.protogen\"\233\001\n" +
      "\004Step\0222\n\tstep_type\030\001 \002(\0162\037.com.anupams.p" +
      "rotogen.Step.Type\022.\n\007element\030\002 \003(\0132\035.com" +
      ".anupams.protogen.Element\"/\n\004Type\022\014\n\010NAV" +
      "IGATE\020\001\022\n\n\006SCRAPE\020\002\022\r\n\tPAGINATED\020\003\"\300\001\n\007E" +
      "lement\022\n\n\002id\030\001 \002(\t\0223\n\tsearch_by\030\002 \002(\0162 ." +
      "com.anupams.protogen.Element.By\022\r\n\005value" +
      "\030\003 \002(\t\0228\n\020relative_element\030\004 \003(\0132\036.com.a" +
      "nupams.protogen.Relative\"+\n\002By\022\t\n\005XPATH\020" +
      "\000\022\007\n\003CSS\020\001\022\006\n\002ID\020\002\022\t\n\005CLASS\020\003\"N\n\010Relativ",
      "e\022\021\n\tparent_id\030\001 \002(\t\022/\n\010elements\030\002 \003(\0132\035" +
      ".com.anupams.protogen.Element"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_anupams_protogen_Step_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_anupams_protogen_Step_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_anupams_protogen_Step_descriptor,
              new java.lang.String[] { "StepType", "Element", },
              com.anupams.protogen.Scrape.Step.class,
              com.anupams.protogen.Scrape.Step.Builder.class);
          internal_static_com_anupams_protogen_Element_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_anupams_protogen_Element_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_anupams_protogen_Element_descriptor,
              new java.lang.String[] { "Id", "SearchBy", "Value", "RelativeElement", },
              com.anupams.protogen.Scrape.Element.class,
              com.anupams.protogen.Scrape.Element.Builder.class);
          internal_static_com_anupams_protogen_Relative_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_anupams_protogen_Relative_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_anupams_protogen_Relative_descriptor,
              new java.lang.String[] { "ParentId", "Elements", },
              com.anupams.protogen.Scrape.Relative.class,
              com.anupams.protogen.Scrape.Relative.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
