import com.anupams.protogen.Scrape;

import java.io.IOException;


/**
 * TODO: Insert description here. (generated by anupams)
 */
public class Main {

  public static void main(String args[]) throws IOException {
    Scrape.Step.Builder builder = Scrape.Step.newBuilder();
  }
}
